name: Build & Push rivals fork
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
jobs:
  mastodon-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta Mastodon
        id: meta_mastodon
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/rivals-space/rivals-mastodon
      - name: Docker meta Nginx
        id: meta_nginx
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/rivals-space/rivals-nginx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Mastodon
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_mastodon.outputs.tags }}
          labels: ${{ steps.meta_mastodon.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Nginx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/nginx/Dockerfile
          push: true
          build-args: |
            MASTODON_CONTAINER=${{ steps.meta_mastodon.outputs.tags }}
          target: nginx
          platforms: linux/amd64
          tags: ${{ steps.meta_nginx.outputs.tags }}
          labels: ${{ steps.meta_nginx.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
